spring:
  application:
    name: EventsManagement

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/events_management?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
#    TODO: HIDE YOUR SENSITIVE INFORMATION WHEN YOU GO LIVE!!!
    username: root
    password: 2605

  jpa:
    hibernate:
      ddl-auto: update


    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: never